// I soci che combattono. Per aggiungerne uno: copia un blocco, cambia look e moves.
// kind delle mosse: lightning | drill | wrench | sleep | pillow | board | cone | shirt | blazer | sneaker | macaw | parakeet | flock | arrow | firearrow | bullet  (vedi PROJECTILES in art.js)
// dmg = danno al boss (il boss ha 180 punti vita), stun = millisecondi in cui il boss resta addormentato.
// outfit.style: 'vest' (elettricista) | 'apron' (commesso di ferramenta) | 'cowboy' (pistolero) | 'coach' (allenatore) | 'stylist' | 'jungle' (uomo della giungla) | (omesso = giacca)

export const FIGHTERS = [
  {
    id: 'michele',
    name: 'MIWOKI',
    look: {
      skin: '#dfac84',
      eye: '#4a3224',
      hair: '#1d1511',
      hairStyle: 'cap-back',
      cap: '#17181c',
      capBand: '#f1f5f9',
      brows: 'thick',
      browColor: '#1d1511',
      beard: '#4a372c',
      beardStyle: 'stubble',
      smile: 'soft',
      gloves: '#dc2626',
      glovesRear: '#dc2626',
      outfit: {
        style: 'vest',
        jacket: '#475569', jacketDark: '#334155', shirt: '#dfac84',
        vest: '#dc2626', vestDark: '#18181b', belt: '#6b4423',
        pants: '#27272a', shoes: '#18181b',
      },
    },
    moves: [
      { kind: 'lightning', label: 'PUGNI FULMINE!', dmg: 3.2 },
      { kind: 'drill', label: 'TRAPANO ROSSO!', dmg: 4 },
    ],
  },
  {
    id: 'luca',
    name: 'LUCA MANCA',
    look: {
      skin: '#e6b28f',
      eye: '#6f8f78',
      hair: '#3a281d',
      hairStyle: 'wavy',
      brows: 'thick',
      browColor: '#3a281d',
      beard: '#a07c58',
      mustache: '#8a6544',
      patch: '#bdb7ac',
      beardStyle: 'mustache-patch',
      glasses: 'rect-thick',
      frame: '#2f3b34',
      lens: 'rgba(220,238,235,.28)',
      smile: 'lips',
      rearHold: 'pillow',
      outfit: {
        style: 'apron', sleeve: 'short',
        jacket: '#e2e8f0', jacketDark: '#cbd5e1', shirt: '#e6b28f',
        apron: '#b7873f', apronDark: '#7c5a22',
        pants: '#334155', shoes: '#4a3426',
      },
    },
    moves: [
      { kind: 'wrench', label: 'CHIAVE INGLESE!', dmg: 2.8 },
      { kind: 'pillow', label: 'CUSCINO KO!', dmg: 3.4 },
      { kind: 'wrench', label: 'CHIAVE INGLESE!', dmg: 2.8 },
      { kind: 'sleep', label: 'NUVOLA DEL SONNO!', dmg: 1.5, stun: 1400 },
    ],
  },
  {
    id: 'roberto',
    name: 'ROBERTO SQUEO',
    look: {
      skin: '#e3b08a',
      hair: '#17110e',
      hairStyle: 'cowboy',
      hat: '#a8743a',
      hatBand: '#3b2412',
      brows: 'thick',
      browColor: '#17110e',
      beard: '#5a2e20',
      beardStyle: 'full',
      glasses: 'rect-thick',
      frame: '#8a3f1b',
      lens: '#14100e',
      smile: 'smirk',
      frontHold: 'bow',
      gloves: '#5b3a1c',
      glovesRear: '#5b3a1c',
      outfit: {
        style: 'cowboy',
        jacket: '#e7d3b0', jacketDark: '#cdb68c', shirt: '#e3b08a',
        vest: '#8a5a2b', vestDark: '#3b2412', bandana: '#dc2626', belt: '#3b2412',
        pants: '#3b5b8c', shoes: '#5b3a1c',
      },
    },
    moves: [
      { kind: 'arrow', label: 'FRECCIA!', dmg: 3 },
      { kind: 'bullet', label: 'COLPO DI REVOLVER!', dmg: 3.4 },
      { kind: 'firearrow', label: 'FRECCIA DI FUOCO!', dmg: 4.2 },
      { kind: 'arrow', label: 'FRECCIA!', dmg: 3 },
    ],
  },
  {
    id: 'nello',
    name: 'NELLO LORUSSO',
    look: {
      skin: '#dba988',
      eye: '#4a3224',
      hair: '#2a211c',
      hairStyle: 'bald',
      brows: 'thick',
      browColor: '#2a211c',
      beard: '#2c231e',
      streak: '#9a948c',
      beardStyle: 'dense',
      earring: '#e5e7eb',
      smile: 'lips',
      rearHold: 'board',
      outfit: {
        style: 'coach',
        jacket: '#2563eb', jacketDark: '#1e3a8a', trim: '#f8fafc', shirt: '#dba988',
        pants: '#1e3a8a', pantStripe: '#f8fafc', shoes: '#f1f5f9',
      },
    },
    moves: [
      { kind: 'board', label: 'LAVAGNETTA TATTICA!', dmg: 3.2 },
      { kind: 'cone', label: 'CONO DA ALLENAMENTO!', dmg: 2.8 },
      { kind: 'board', label: 'LAVAGNETTA TATTICA!', dmg: 3.2 },
      { kind: 'cone', label: 'CONO DA ALLENAMENTO!', dmg: 2.8 },
    ],
  },
  {
    id: 'saverio',
    name: 'SAVERIO',
    look: {
      skin: '#c98f68',
      eye: '#2a1810',
      hair: '#0f0d0c',
      hairStyle: 'swept',
      brows: 'thick',
      browColor: '#0f0d0c',
      beard: '#2a1d17',
      beardStyle: 'stubble',
      earring: '#d6b48a',
      earring2: true,
      smile: 'soft',
      rearHold: 'hanger',
      outfit: {
        style: 'stylist',
        jacket: '#c8a27a', jacketDark: '#8b6a46', shirt: '#18181b',
        pants: '#e5dfd0', shoes: '#18181b',
      },
    },
    moves: [
      { kind: 'shirt', label: 'T-SHIRT LANCIATA!', dmg: 2.8 },
      { kind: 'blazer', label: 'GIACCA OVERSIZE!', dmg: 3.6 },
      { kind: 'sneaker', label: 'SNEAKER LIMITED!', dmg: 3.2 },
      { kind: 'shirt', label: 'T-SHIRT LANCIATA!', dmg: 2.8 },
    ],
  },
  {
    id: 'borrello',
    name: 'RE DELLA GIUNGLA',   // Borrello
    look: {
      skin: '#b9825a',
      eye: '#2a1810',
      hair: '#17110e',
      hairStyle: 'crop',
      brows: 'thick',
      browColor: '#17110e',
      beard: '#241a15',
      streak: '#8d8780',
      beardStyle: 'dense',
      glasses: 'rect-thick',
      frame: '#0b0b0f',
      lens: 'rgba(220,235,240,.22)',
      smile: 'lips',
      outfit: {
        style: 'jungle',
        jacket: '#b9825a', jacketDark: '#b9825a', shirt: '#b9825a',
        fur: '#d9a441', vine: '#4d7c0f',
        pants: '#b9825a', shoes: '#a8704a',
      },
    },
    moves: [
      { kind: 'macaw', label: 'ARA ROSSA!', dmg: 3.4 },
      { kind: 'parakeet', label: 'PAPPAGALLINO!', dmg: 2.6 },
      { kind: 'flock', label: 'STORMO DI PAPPAGALLI!', dmg: 4.4 },
      { kind: 'macaw', label: 'ARA ROSSA!', dmg: 3.4 },
    ],
  },
]
